// Generate lib/guides/content.generated.ts from the raw HTML files in content/guides/.
// These guide pages are standalone HTML (own fonts/CSS) migrated from taip.io.
// We embed them as a bundled TS module so the standalone Docker image always
// ships them (runtime fs/tracing is unreliable in the prod image).
//
// Run after adding/editing a file in content/guides/:
//   node scripts/generate-guides.mjs
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(root, "content", "guides");
const outFile = join(root, "lib", "guides", "content.generated.ts");

const files = readdirSync(srcDir)
  .filter((f) => f.endsWith(".html"))
  .sort();

const entries = files.map((f) => {
  const slug = f.replace(/\.html$/, "");
  const html = readFileSync(join(srcDir, f), "utf8");
  // JSON.stringify safely escapes quotes, backslashes, newlines, etc.
  return `  ${JSON.stringify(slug)}: ${JSON.stringify(html)},`;
});

const out = `// AUTO-GENERATED by scripts/generate-guides.mjs — do not edit by hand.
// Source: content/guides/*.html
export const GUIDES: Record<string, string> = {
${entries.join("\n")}
};

export const GUIDE_SLUGS = Object.keys(GUIDES);
`;

writeFileSync(outFile, out, "utf8");
console.log(`Wrote ${files.length} guides -> ${outFile}`);
